apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-add-deployment
  namespace: nextjs-add2num
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-add
  template:
    metadata:
      labels:
        app: nextjs-add
    spec:
      containers:
        - name: nextjs-add2num
          image: nextjs-add2num:latest
          env: 
            - name: HOSTNAME
              value: "0.0.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000