apiVersion: v1
kind: Service
metadata:
  name: nextjs-add-service
  namespace: nextjs-add2num
spec:
  selector:
    app: nextjs-add
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort